export const POSTS_LOADING = 'POSTS_LOADING';
export type POSTS_LOADING = typeof POSTS_LOADING;
export const POSTS_LOADED ='POSTS_LOADED';
export type POSTS_LOADED =typeof POSTS_LOADED;
export const POSTS_LOADING_ERROR ='POSTS_LOADING_ERROR'; 
export type POSTS_LOADING_ERROR=typeof POSTS_LOADING_ERROR;